[[pages]]
path = "app.py"
name = "Dashboard"

[[pages]]
path = "pages/1_Equity_Scout.py"
name = "Equity Scout"

[[pages]]
path = "pages/2_Market_Screener.py"
name = "Market Screener"

[[pages]]
path = "pages/3_Financial_Modeler.py"
name = "Financial Modeler"

[[pages]]
path = "pages/4_MS_Financial_Modeler.py"
name = "MS Financial Modeler"

[[pages]]
path = "pages/5_Downloads.py"
name = "Downloads"

[[pages]]
path = "pages/6_Punch_List.py"
name = "Punch List"
